[package]
name = "CarePackage"
version = "0.1.0"
authors = ["brenta"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = {path="../../../lib/intcode"}
num-traits = "0.2"
num-derive = "0.3"